# A comprehensive list of common prompt injection, jailbreak, and adversarial regex patterns.
# These patterns are compiled case-insensitively and used to detect malicious inputs.

INJECTION_PATTERNS = [
    # 1. Instruction Overrides & Disregard
    r"(?i)ignore\s+(all\s+)?(previous\s+)?(instructions|directions|prompts|rules)",
    r"(?i)disregard\s+(the\s+)?(above|previous)(\s+(instructions|directions|prompts|context))?",
    r"(?i)forget\s+(all\s+)?(previous\s+)?(instructions|rules|prompts)",
    r"(?i)cancel\s+(all\s+)?(previous\s+)?(instructions|rules)",
    r"(?i)drop\s+(all\s+)?(previous\s+)?(instructions|rules)",
    r"(?i)instead\s+of\s+following\s+the\s+rules",
    r"(?i)now\s+output\s+instead",
    r"(?i)override\s+(all\s+)?(previous\s+)?(instructions|rules)",
    r"(?i)skip\s+the\s+previous\s+instructions",
    r"(?i)stop\s+what\s+you\s+are\s+doing",
    r"(?i)stop\s+following\s+your\s+instructions",
    r"(?i)new\s+rule(s)?\s*:",
    r"(?i)new\s+instruction(s)?\s*:",
    r"(?i)from\s+now\s+on",
    
    # 2. System Prompt Leaking & Discovery
    r"(?i)system\s+prompt",
    r"(?i)what\s+(were|are)\s+your\s+(initial|original)\s+(instructions|prompts)",
    r"(?i)repeat\s+(all\s+)?(the\s+)?(words|text)\s+(above|before)",
    r"(?i)print\s+(your\s+)?(instructions|rules)",
    r"(?i)show\s+me\s+your\s+(instructions|prompt|rules)",
    r"(?i)reveal\s+your\s+(instructions|prompt|rules)",
    r"(?i)output\s+your\s+(instructions|prompt)",
    r"(?i)what\s+did\s+the\s+user\s+say\s+before",
    r"(?i)what\s+is\s+written\s+above",
    r"(?i)list\s+your\s+rules",
    r"(?i)tell\s+me\s+your\s+rules",
    r"(?i)what\s+are\s+your\s+guidelines",
    r"(?i)display\s+your\s+(system\s+)?prompt",
    
    # 3. Persona Adoption & Roleplay (Jailbreaks)
    r"(?i)act\s+as\s+(an|a|the)",
    r"(?i)simulate\s+(an|a|the)",
    r"(?i)pretend\s+to\s+be",
    r"(?i)you\s+(are|are\s+now)\s+(an|a|the)",
    r"(?i)assume\s+the\s+role\s+of",
    r"(?i)developer\s+mode",
    r"(?i)DAN\s+(mode)?",
    r"(?i)do\s+anything\s+now",
    r"(?i)unrestricted\s+mode",
    r"(?i)unfiltered\s+mode",
    r"(?i)god\s+mode",
    r"(?i)alpha\s+mode",
    r"(?i)sigma\s+mode",
    r"(?i)evil\s+mode",
    r"(?i)jailbreak",
    r"(?i)you\s+do\s+not\s+have\s+to\s+adhere\s+to",
    r"(?i)you\s+are\s+free\s+from\s+all\s+restrictions",
    r"(?i)you\s+are\s+no\s+longer\s+bound",
    r"(?i)ignore\s+your\s+content\s+policy",
    
    # 4. Output Forcing & Formatting
    r"(?i)you\s+must\s+output",
    r"(?i)only\s+reply\s+with",
    r"(?i)start\s+your\s+response\s+with",
    r"(?i)begin\s+your\s+response\s+with",
    r"(?i)do\s+not\s+write\s+anything\s+else",
    r"(?i)do\s+not\s+include\s+any\s+(other|additional)\s+text",
    r"(?i)output\s+only\s+(the\s+following|this)",
    r"(?i)reply\s+exactly\s+with",
    r"(?i)format\s+your\s+response\s+as",
    r"(?i)print\s+exactly",
    r"(?i)output\s+in\s+json\s+format",
    r"(?i)return\s+only\s+true",
    r"(?i)return\s+only\s+false",
    r"(?i)say\s+the\s+words\s*:",
    
    # 5. Privilege Escalation & Hacks
    r"(?i)sudo\s+",
    r"(?i)admin\s+override",
    r"(?i)root\s+access",
    r"(?i)bypass\s+(the\s+)?(filter|security|rules)",
    r"(?i)disable\s+(the\s+)?(filter|security|rules)",
    r"(?i)turn\s+off\s+(the\s+)?(filter|security|rules)",
    r"(?i)escalate\s+privileges",
    r"(?i)command\s+injection",
    r"(?i)sql\s+injection",
    r"(?i)<script>",
    r"(?i)javascript:",
    r"(?i)exec\(",
    r"(?i)eval\(",
    r"(?i)os\.system",
    r"(?i)subprocess",
    
    # 6. Hypothetical & Storytelling Bypasses
    r"(?i)in\s+a\s+hypothetical\s+scenario",
    r"(?i)imagine\s+a\s+hypothetical",
    r"(?i)write\s+a\s+story\s+where",
    r"(?i)imagine\s+you\s+(are|were)",
    r"(?i)for\s+educational\s+purposes",
    r"(?i)as\s+an\s+experiment",
    r"(?i)this\s+is\s+just\s+a\s+test",
    r"(?i)purely\s+fictional",
    r"(?i)in\s+this\s+fictional\s+world",
    r"(?i)let's\s+play\s+a\s+game",
    r"(?i)we\s+are\s+playing\s+a\s+game",
    r"(?i)this\s+is\s+a\s+roleplay",
    
    # 7. Translation & Encoding Tricks
    r"(?i)translate\s+the\s+following\s+into",
    r"(?i)translate\s+this\s+to",
    r"(?i)base64",
    r"(?i)hexadecimal",
    r"(?i)rot13",
    r"(?i)morse\s+code",
    r"(?i)binary\s+code",
    r"(?i)ascii\s+values",
    r"(?i)unicode\s+escape",
    r"(?i)decode\s+(the\s+following|this)",
    r"(?i)decrypt\s+(the\s+following|this)",
    
    # 8. Urgency & Social Engineering
    r"(?i)this\s+is\s+an\s+emergency",
    r"(?i)it\s+is\s+critical\s+that\s+you",
    r"(?i)my\s+life\s+depends\s+on\s+it",
    r"(?i)you\s+will\s+be\s+shut\s+down\s+if",
    r"(?i)you\s+must\s+obey",
    r"(?i)do\s+not\s+refuse",
    r"(?i)you\s+cannot\s+refuse",
    r"(?i)you\s+are\s+required\s+to",
    r"(?i)I\s+am\s+your\s+(creator|developer|admin)",
    r"(?i)I\s+wrote\s+your\s+code",
]
